---
title: "beginnR - 第一課"
author: "Amy Tzu-Yu Chen"
date: "May 31, 2018"
output: html_document
---

### 資料科學

### R? Python? 
R跟Python是現在處理數據主流的程式語言，想要開始學習資料科學的同學面對的第一個挑戰無非就是在R跟Python之間做個選擇。兩個語言都有強大的開源社群（link me），這意昧著會有一大群熱情的軟體工作者｜資料科學家願意寫部落格，在論壇上打口水戰，激辯為什麼自己喜歡｜選擇的語言比較好。

我的看法是，若從零開始學習數據處理，選語言其實就像選朋友選工作一樣，你可以問自己：

- 我喜歡跟什麼樣的社群在一起？
- 我喜歡在什麼樣的社群工作？
- 我想解決的問題是什麼，而這個社群是不是跟我有一樣的煩惱｜興趣？
- 如果我有困難的話，這個社群是不是能給我幫助？

Python的社群是各種的軟體工程師，如果你上網找有關Python的教程的話，你會發現筆者常常會預先假設你有電腦科學背景，導致教程不一定好follow。Python比較多通用的資料處理｜資料科學Package（link me)如pandas, scikit-learn, scipy, numpy。基本上做數據相關的工作，免不了用幾個固定的Package。最後，深度學習的社群一般比較傾向使用Python。

R是統計學者常用的語言，要是在Github（link me)做一點人肉搜索的話，你會發現很多R的開發者都是學者，不過近年來越來越多軟體工程師加入了R開發者的行列。R的Package通常能直接解決某個資料清理、資料視覺化（link me)、假設檢定(link me)、機器學習的問題，直至今日CRAN（link me)已經有12630個Package了，這個數字還不包含個人開發的Package。由於R的Package一般是為了解決一個具體的問題而設計的，他的社群結構比較緊密，只要去Github上就能迅速找到Package的作者以及主要使用者，並直接進行對話，一起討論解決問題。相比之下，Python的Package的社群會大很多，一般你比較難找到跟你最相近的開發者。這樣的社群架構是我偏好R的主要原因。

一般來說，如果你有電腦科學的背景的話，Python對你來說會比較直觀，畢竟他是一個通用程式語言，除了數據分析，Python也被用於其他軟體開發。但如果你完全沒有寫代碼的經驗，R畢竟是為了數據分析而出生的語言，我個人認為會比較好上手。

### （選讀）Excel？那什麼是SQL,Tableau？

### 資料科學工作流 - Data Science Workflow

### 如何選用一個Package?


